config/routes.rb
Rails.application.routes.draw do

  resources :tasks

  root :to => 'home#index'

  get 'tasks/:id/assign' => 'tasks#assign'
  get 'tasks/:id/status' => 'tasks#status'
  get 'tasks/:id/assign_to_me' => 'tasks#assign_to_me'

  devise_for :employees, :controllers => {registrations: 'registrations'}
  resources :employees

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@tasks = Task.all
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <% if not only_my_tasks %>
        <th>Assignee</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% if not only_my_tasks or task.assignee == current_employee.id %>
        <tr>
          <td><%= task.name %></td>
          <td><%= task.description %></td>
          <td><%= task.status %></td>
          <% if not only_my_tasks %>
            <td>
              <% if task.assignee != nil %>
                <%= Employee.find(task.assignee).full_name %>
              <% else %>
                Unassigned
              <% end %>
            </td>
          <% end %>
          <td><%= link_to 'Show', task %></td>
          <% if is_manager? %>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
            <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'Assign', assign_task_path(task) %></td>
          <% else %>
            <td><%= link_to 'Change status', change_status_path(task) %></td>
            <% if task.assignee == current_employee.id %>
              <td><%= link_to 'Assign to manager', assign_task_path(task) %></td>
            <% else %>
              <td><%= link_to 'Assign to me', assign_to_me_path(task) %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1>Welcome <%= current_employee.first_name %></h1>

<h2>My Tasks</h2>
<%= render :partial => 'table', :locals => {:only_my_tasks => true} %>

<h2>All Tasks</h2>
<%= render :partial => 'table', :locals => {:only_my_tasks => false} %>


<%= link_to "Employees", employees_path %>
<%= link_to "New task", new_task_path %>